### ISSUE TITLE
Unexpected API Response: {"detail":"Not Found"}

### ISSUE THREAD

**Issue by ghost** [AndBobsYourUncle/stable-diffusion-discord-bot#37]
<img width="529" alt="See this please" src="https://github.com/AndBobsYourUncle/stable-diffusion-discord-bot/assets/96412050/f3c2f053-de16-492c-8f2c-db939b227c52">

Please help me. The Stable Diffusion is working very-well on my (URL): http://XXX:$PORT. But, the Discord bot showing that error. It says not found, does that mean the location has been changed?

Thanks.

**Comment by ghost** [comment]
Issue has been solved.

**Comment by itstaylorham** [comment]
What was the solution for this?

**Comment by itstaylorham** [comment]
> Issue has been solved.

What was the solution?
